services:
  lac-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_lac
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#Spdc2026#
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: